import { Payment, columns } from './columns';
import { DataTable } from './data-table';

const getData = async (): Promise<Payment[]> => {
  return [
    {
      id: '728ed521',
      amount: 134,
      status: 'pending',
      fullName: 'Omar Monib',
      useID: "1",
      email: 'OmarMonib@gmail.com',
    },
    {
      id: '728ed522',
      amount: 124,
      status: 'success',
      fullName: 'Jane Doe',
      useID: "2",
      email: 'janedoe@gmail.com',
    },
    {
      id: '728ed523',
      amount: 167,
      status: 'success',
      fullName: 'Mike Galloway',
      useID: "3",
      email: 'mikegalloway@gmail.com',
    },
    {
      id: '728ed524',
      amount: 156,
      status: 'failed',
      fullName: 'Minerva Robinson',
      useID: "4",
      email: 'minerbarobinson@gmail.com',
    },
    {
      id: '728ed525',
      amount: 145,
      status: 'success',
      fullName: 'Mable Clayton',
      useID: "5",
      email: 'mableclayton@gmail.com',
    },
    {
      id: '728ed526',
      amount: 189,
      status: 'pending',
      fullName: 'Nathan McDaniel',
      useID: "6",
      email: 'nathanmcdaniel@gmail.com',
    },
    {
      id: '728ed527',
      amount: 178,
      status: 'success',
      fullName: 'Myrtie Lamb',
      useID: "7",
      email: 'myrtielamb@gmail.com',
    },
    {
      id: '728ed528',
      amount: 190,
      status: 'success',
      fullName: 'Leona Bryant',
      useID: "8",
      email: 'leonabryant@gmail.com',
    },
    {
      id: '728ed529',
      amount: 134,
      status: 'failed',
      fullName: 'Aaron Willis',
      useID: "9",
      email: 'aaronwillis@gmail.com',
    },
    {
      id: '728ed52a',
      amount: 543,
      status: 'success',
      fullName: 'Joel Keller',
      useID: "10",
      email: 'joelkeller@gmail.com',
    },
    {
      id: '728ed52b',
      amount: 234,
      status: 'pending',
      fullName: 'Daniel Ellis',
      useID: "11",
      email: 'danielellis@gmail.com',
    },
    {
      id: '728ed52c',
      amount: 345,
      status: 'success',
      fullName: 'Gordon Kennedy',
      useID: "12",
      email: 'gordonkennedy@gmail.com',
    },
    {
      id: '728ed52d',
      amount: 335,
      status: 'failed',
      fullName: 'Emily Hoffman',
      useID: "13",
      email: 'emilyhoffman@gmail.com',
    },
    {
      id: '728ed52e',
      amount: 664,
      status: 'pending',
      fullName: 'Jeffery Garrett',
      useID: "14",
      email: 'jefferygarrett@gmail.com',
    },
    {
      id: '728ed52f',
      amount: 332,
      status: 'success',
      fullName: 'Ralph Baker',
      useID: "15",
      email: 'ralphbaker@gmail.com',
    },
    {
      id: '728ed52g',
      amount: 413,
      status: 'failed',
      fullName: 'Seth Fields',
      useID: "16",
      email: 'sethfields@gmail.com',
    },
    {
      id: '728ed52h',
      amount: 345,
      status: 'pending',
      fullName: 'Julia Webb',
      useID: "17",
      email: 'juliawebb@gmail.com',
    },
    {
      id: '728ed52i',
      amount: 754,
      status: 'success',
      fullName: 'Gary Banks',
      useID: "18",
      email: 'garybanks@gmail.com',
    },
    {
      id: '728ed52j',
      amount: 643,
      status: 'failed',
      fullName: 'Flora Chambers',
      useID: "19",
      email: 'florachambers@gmail.com',
    },
    {
      id: '728ed52k',
      amount: 543,
      status: 'pending',
      fullName: 'Steve Hanson',
      useID: "20",
      email: 'stevehanson@gmail.com',
    },
    {
      id: '728ed52l',
      amount: 324,
      status: 'success',
      fullName: 'Lola Robinson',
      useID: "21",
      email: 'lolarobinson@gmail.com',
    },
    {
      id: '728ed52m',
      amount: 123,
      status: 'pending',
      fullName: 'Ethel Waters',
      useID: "22",
      email: 'ethelwaters@gmail.com',
    },
    {
      id: '728ed52n',
      amount: 422,
      status: 'failed',
      fullName: 'Grace Edwards',
      useID: "23",
      email: 'graceedwards@gmail.com',
    },
    {
      id: '728ed52o',
      amount: 712,
      status: 'success',
      fullName: 'Sallie Wong',
      useID: "24",
      email: 'salliewong@gmail.com',
    },
    {
      id: '728ed52p',
      amount: 360,
      status: 'success',
      fullName: 'Bryan Gutierrez',
      useID: "25",
      email: 'bryangutierrez@gmail.com',
    },
    {
      id: '728ed52q',
      amount: 454,
      status: 'pending',
      fullName: 'Erik Rice',
      useID: "26",
      email: 'erikrice@gmail.com',
    },
    {
      id: '728ed52r',
      amount: 382,
      status: 'success',
      fullName: 'Jordan Atkins',
      useID: "27",
      email: 'jordanatkins@gmail.com',
    },
    {
      id: '728ed52s',
      amount: 328,
      status: 'failed',
      fullName: 'Bill Brewer',
      useID: "28",
      email: 'billbrewer@gmail.com',
    },
    {
      id: '728ed52t',
      amount: 250,
      status: 'success',
      fullName: 'Edwin Morris',
      useID: "29",
      email: 'edwinmorris@gmail.com',
    },
    {
      id: '728ed52u',
      amount: 658,
      status: 'success',
      fullName: 'Harold Becker',
      useID: "30",
      email: 'haroldbecker@gmail.com',
    },
    {
      id: '728ed52v',
      amount: 691,
      status: 'success',
      fullName: 'Hannah Rodriguez',
      useID: "31",
      email: 'hannahrodriguez@gmail.com',
    },
    {
      id: '728ed52w',
      amount: 969,
      status: 'success',
      fullName: 'Zachary Beck',
      useID: "32",
      email: 'zacharybeck@gmail.com',
    },
    {
      id: '728ed52x',
      amount: 617,
      status: 'failed',
      fullName: 'Frances Potter',
      useID: "33",
      email: 'francespotter@gmail.com',
    },
    {
      id: '728ed52y',
      amount: 173,
      status: 'success',
      fullName: 'Raymond Murray',
      useID: "34",
      email: 'raymondmurray@gmail.com',
    },
    {
      id: '728ed52z',
      amount: 843,
      status: 'success',
      fullName: 'Adam Sherman',
      useID: "35",
      email: 'adamsherman@gmail.com',
    },
    {
      id: '728ed521f',
      amount: 914,
      status: 'pending',
      fullName: 'Anne Cruz',
      useID: "36",
      email: 'annecruz@gmail.com',
    },
  ];
};

const PaymentsPage = async () => {
  const data = await getData();
  return (
    <div className="">
      <div className="mb-8 px-4 py-2 bg-secondary rounded-md">
        <h1 className="font-semibold">All Payments</h1>
      </div>
      <DataTable columns={columns} data={data} />
    </div>
  );
};

export default PaymentsPage;
